### PR TITLE
Added unzip actions

### PR DESCRIPTION
**Pull request by mochman**
HA 6.0 has some images compressed using zip.  Added a check to the install.sh file to unzip those files.

Issue:
Error when installing Unable to handle file extension 'zip'. #113

### CODE REVIEW

**Comment by AntaeusNar** [comment]
@mochman would it also be a good idea to include a call to install unzip if required?

**Comment by mochman** [comment]
I added a section to check to see if unzip is needed, then install unzip if it's not on the system already.

**Comment by Ajax-online** [comment]
> HA 6.0 has some images compressed using zip. Added a check to the install.sh file to unzip those files.
> 
> Issue:
> Error when installing Unable to handle file extension 'zip'. #113

Hi Thank you for the information . I am totally a newbie and really dont know how to add this, Is there a way you could upload the whole file with Whiskerrz one line code. Thank you

**Comment by mochman** [comment]
> Hi Thank you for the information . I am totally a newbie and really dont know how to add this, Is there a way you could upload the whole file with Whiskerrz one line code. Thank you

Well, until this is merged, you can use the one from my forked repo.
`bash -c "$(wget -qLO - https://github.com/mochman/proxmox_hassos_install/raw/master/install.sh)"
`

**Comment by Eschguy** [comment]
Getting myself set up and ran into the issue. Thanks for making the changes!

**Comment by RobertusIT** [comment]
root@NUCi3:~# bash -c "$(wget -qLO - https://github.com/mochman/proxmox_hassos_install/raw/master/install.sh)"
[INFO] Using 'local-lvm' for storage location.
[INFO] Container ID is 100.
Getting URL for latest Home Assistant disk image...
Downloading disk image...
Checking for unzip command
unzip not found, installing...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package unzip
**[ERROR] 100@115 Unknown failure occured.**

**Comment by mochman** [comment]
> E: Unable to locate package unzip

Have you tried running `apt update` first?  Do you need to `sudo apt install unzip` instead?

**Comment by RobertusIT** [comment]
> > E: Unable to locate package unzip
> 
> Have you tried running `apt update` first? Do you need to `sudo apt install unzip` instead?

yes of course, anyway i use a vm image in proxmox. I'll try with another hard disk, this one is little 32GB.

**Comment by basnijholt** [comment]
@whiskerz007 master is broken, this PR fixes it. Just merge it :)

**Comment by Creat** [comment]
I can confirm that this patch is (still) needed. Just ran in to the same issue. Of the proposed patches, this seems the easiest to accept into the repo, if you're so inclined. Some sort of ZIP support is obviously needed now though.

**Comment by helenclarko** [comment]
I hope @whiskerz007 or @basnijholt see's some of these requests, maybe we can get another administrator on this project to help review some of these.

**Comment by fredrikscode** [comment]
Unzip is not a part of Debian and is an unecessary package to install. Use gunzip to unzip instead since it comes with the OS. Clone my repo or:
`bash -c "$(wget -qLO - https://github.com/fredrikscode/proxmox_hassos_install/raw/master/install.sh)"`

**Pull request closed without merging**
